version: "3"
services:
  pdns-db:
    image: mariadb:10.1
    environment:
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=pdns
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  pdns:
    image: bgpat/docker-pdns:latest
    environment:
      - GMYSQL_DBNAME=pdns
      - GMYSQL_HOST=pdns-db
      - GMYSQL_PORT=3306
      - GMYSQL_USER=pdns
      - GMYSQL_PASSWORD=pdns
      - WEBSERVER=yes
      - API=yes
      - API_KEY=secret
      - MASTER=yes
      - DEFAULT_SOA_NAME=401.jp
    links:
      - pdns-db
    ports:
      - "53:53"
      - "53:53/udp"
  admin-db:
    image: mariadb:10.1
    environment:
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=pdns
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  admin:
    image: bgpat/docker-powerdns-admin:latest
    environment:
      - DATABASE_URI=mysql://pdns:pdns@admin-db/pdns
      - PDNS_STATS_URL=http://pdns:8081
      - PDNS_API_KEY=secret
      - SIGNUP_ENABLED=no
    links:
      - pdns
      - admin-db
    ports:
      - "127.0.0.1:9393:9393"
